### ISSUE TITLE
Import into Uniface

### ISSUE THREAD

**Issue by MaxChaza** [uniface/WASListener#8]
Hello,
In order to version Uniface XML exports we use WAS listener.
The tool is very good for exporting to xml but has some limitations when it comes to importing.
Indeed for the moment it is only possible to do a global import of the WorkArea folder.

**Would it be possible to detect changes in the xml files, so that only the modified and selected xml can be imported?**

Thanks

**Comment by uf-mtaylor** [comment]
The utility is in two parts

1. A Uniface plugin that allows you to export or revert changes in your repository.
2. A listener (WASListener.exe) process which watches the source folder (must me local) and automatically synchronises file changes with the Uniface repository. 

For information about how to configure the WASListener.exe process you can see either the included readme.html or the plugin page on the Uniface community site. https://community.rocketsoftware.com/viewdocument/work-area-support-utility?CommunityKey=8a320023-2402-4fd6-b71d-6224c43259e8

I hope this helps
