### ISSUE TITLE
Configure WASlistener so that UTIMESTAMP and UCOMPSTAMP are not stored in XML

### ISSUE THREAD

**Issue by MaxChaza** [uniface/WASListener#9]
Hello, 
I use your tool to do git versionning on xml files.
UTIMESTAMP and UCOMPSTAMP drive many useless conficts on when merging code.
Is it possible to manage WASlistener to not store UTIMESTAMP and UCOMPSTAMP in XML.
Thanks in advance,
Maxime CHAZALVIEL

**Comment by uf-mtaylor** [comment]
UTIMESTAMP is used to determine if the source has changed in the Uniface repository and to display the list of modified items. 
UCOMPSTAMP is no longer used in version, 10 so should not be causing an issue.

I would like to understand the steps that are taken that demonstrate the issues - is this something you can supply me?
Many thanks
